AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 instance
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      KeyName: 'ansible_key'  # Replace with your key pair name
      ImageId: 'ami-0bb84b8ffd87024d8'  # Replace with a valid AMI ID for your region
      SecurityGroups:
        - Ref: MySecurityGroup

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: 'tcp'
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'
        - IpProtocol: 'tcp'
          FromPort: '80'
          ToPort: '80'
          CidrIp: '0.0.0.0/0'